# Generated by Django 2.1.4 on 2019-02-08 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('sub_titulo', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('conteudo', models.TextField(max_length=3000)),
                ('capa', models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location)),
                ('rascunho', models.BooleanField(default=False)),
                ('publish', models.DateField()),
                ('lancado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado', '-lancado'],
            },
        ),
    ]
