# Generated by Django 2.1.4 on 2019-02-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='publicar_em',
        ),
    ]
