# Generated by Django 2.1.4 on 2019-02-09 12:19

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190208_2238'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('posts', django.db.models.manager.Manager()),
            ],
        ),
    ]
