# Generated by Django 2.1.4 on 2019-02-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190209_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-atualizado', '-criado']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='lancado',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publicar_em',
            new_name='data_lancamento',
        ),
    ]
