# Generated by Django 2.1.4 on 2019-02-07 22:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190207_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2019, 2, 7, 22, 52, 41, 710992, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
