# Generated by Django 2.1.4 on 2019-02-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rascunho',
            field=models.BooleanField(default=False),
        ),
    ]
